{"source": "exploit-database", "filename": "platforms/linux/local/38832.py", "cves": ["CVE-2015-5287"]}